-- These are default values that will be loaded when player first time joins the game.

return {
    Inventory = {
        --[[
			List items there as:
			"ItemName",
			"ItemName",
			"ItemName",
			...
		]]
    },
    Values = {
        Money = 0,
        EXP = 0,
        Level = 0,
        SkillPoints = 0,
    },
    Stats = {
        HP = 0,
        MP = 0,
        STR = 0,
        DEX = 0,
        LUK = 0,
        INT = 0,
    },
}
