return {
	volume = {
		button1 = {
			BackgroundColor = Color3.fromRGB(0, 0, 0),
			ImageId = "rbxassetid://114890445206078",
		},
	},
	friends = {
		button1 = {
			BackgroundColor = Color3.fromRGB(0, 0, 0),
			ImageId = "rbxassetid://114890445206078",
		},
		button2 = {
			BackgroundColor = Color3.fromRGB(36, 136, 250),
			ImageId = "rbxassetid://133151524475194",
		},
	},
	settings = {
		button1 = {
			BackgroundColor = Color3.fromRGB(0, 0, 0),
			ImageId = "rbxassetid://114890445206078",
		},
	},
	messages = {
		button1 = {
			BackgroundColor = Color3.fromRGB(0, 0, 0),
			ImageId = "rbxassetid://114890445206078",
		},
		button2 = {
			BackgroundColor = Color3.fromRGB(0, 132, 255),
			ImageId = "rbxassetid://130398508392116",
		},
	},
	newchatmenu = {
		button1 = {
			BackgroundColor = Color3.fromRGB(48, 48, 48),
			ImageId = "rbxassetid://116870917498847",
		},
		button2 = {
			BackgroundColor = Color3.fromRGB(36, 136, 250),
			ImageId = "rbxassetid://133151524475194",
		},
	},
	chat = {
		button1 = {
			BackgroundColor = Color3.fromRGB(48, 48, 48),
			ImageId = "rbxassetid://116870917498847",
		},
		button2 = {
			BackgroundColor = Color3.fromRGB(0, 198, 23),
			ImageId = "rbxassetid://102503786262211",
		},
	},
}
