return {
    volume = {
        button1 = {
            BackgroundColor = Color3.fromRGB(0, 0, 0),
            ImageId = "rbxassetid://114890445206078",
        },
    },
    friends = {
        button1 = {
            BackgroundColor = Color3.fromRGB(0, 0, 0),
            ImageId = "rbxassetid://114890445206078",
        },
        button2 = {
            BackgroundColor = Color3.fromRGB(36, 136, 250),
            ImageId = "rbxassetid://133151524475194",
        },
    },
}
