return {
    MinimumCharacters = 3,
    MaximumCharacter = 12,
    MinimumCharactersWarningMessage = "Username should contain at least %d characters.",
    MaximumCharactersWarningMessage = "Maximum characters reached.",
    SpecialCharactersWarningMessage = "Username can't have special characters.",
    SpaceWarningMessage = "Username can't have spaces.",
    UnderscoreWarningMessage = "Username can't have an underscore.",
}
