local ReplicatedStorage = game:GetService("ReplicatedStorage")

return {
    NebulaOrb = {
        DisplayName = "Nebula Orb",
        Image = "rbxassetid://105316741105719",
        Class = "Item",
        Rarity = "Common",
    },
    MedallionTiger = {
        DisplayName = "Medallion Tiger",
        Image = "rbxassetid://92390685016112",
        Class = "Item",
        Rarity = "Common",
    },
    MedallionShark = {
        DisplayName = "Medallion Shark",
        Image = "rbxassetid://91714249972584",
        Class = "Item",
        Rarity = "Common",
    },
    MedallionMosquito = {
        DisplayName = "Medallion Mosquito",
        Image = "rbxassetid://102673775383822",
        Class = "Item",
        Rarity = "Common",
    },
    MedallionJellyfish = {
        DisplayName = "Medallion Jellyfish",
        Image = "rbxassetid://109597987624466",
        Class = "Item",
        Rarity = "Common",
    },
    MedallionHawk = {
        DisplayName = "Medallion Hawk",
        Image = "rbxassetid://115326385132458",
        Class = "Item",
        Rarity = "Common",
    },
    MedallionFroghopper = {
        DisplayName = "Medallion Froghopper",
        Image = "rbxassetid://76645989344410",
        Class = "Item",
        Rarity = "Common",
    },
    MedallionElephant = {
        DisplayName = "Medallion Elephant",
        Image = "rbxassetid://103895985412285",
        Class = "Item",
        Rarity = "Common",
    },
    MedallionBear = {
        DisplayName = "Medallion Bear",
        Image = "rbxassetid://131363926799582",
        Class = "Item",
        Rarity = "Common",
    },
    MedallionAxolotl = {
        DisplayName = "Medallion Axolotl",
        Image = "rbxassetid://114226439122993",
        Class = "Item",
        Rarity = "Common",
    },
    MedallionAnimals = {
        DisplayName = "Medallion Animals",
        Image = "rbxassetid://139098524570712",
        Class = "Item",
        Rarity = "Common",
    },
    GoldDiamond = {
        DisplayName = "Gold Diamond",
        Image = "rbxassetid://84928570291523",
        Class = "Item",
        Rarity = "Common",
    },
    TraeScottieMochaLow1s = {
        DisplayName = "Trae Scottie Mocha Low 1s",
        Image = "rbxassetid://131663049024652",
        Unstackable = true,
        Model = ReplicatedStorage:WaitForChild("Assets").Models.Shoes.TraeScottieMochaLow1s,
        Rarity = "Common",
    },
}
